name: Build Android app

on:
  push:
    tags:
      - build-*
      - buildandroid-*

jobs:
  build-android:
    name: Build release AAB and APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Create my-upload-key.keystore file
        env:
          MY_UPLOAD_KEY_KEYSTORE_BASE64: ${{ secrets.MY_UPLOAD_KEY_KEYSTORE_BASE64 }}
        run: echo $MY_UPLOAD_KEY_KEYSTORE_BASE64 | base64 -d > android/app/my-upload-key.keystore
      - name: Create gradle.properties file
        env:
          GRADLE_PROPERTIES_BASE64: ${{ secrets.GRADLE_PROPERTIES_BASE64 }}
        run: mkdir -p ~/.gradle && echo $GRADLE_PROPERTIES_BASE64 | base64 -d > ~/.gradle/gradle.properties
      - name: Build AAB and APK
        run: cd android && ./gradlew clean assembleRelease bundleRelease
      - name: Upload AAB and APK artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-binaries
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/bundle/release/app-release.aab
